"""empty message

Revision ID: 62d6957e3cc9
Revises: a5ec59537ce6
Create Date: 2022-11-29 14:38:51.949297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d6957e3cc9'
down_revision = 'a5ec59537ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=20), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('college_course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_college_course_professor_id'), ['professor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college_course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_college_course_professor_id'))

    op.drop_table('college_course')
    # ### end Alembic commands ###
