"""empty message

Revision ID: d1b1f11fe898
Revises: 62d6957e3cc9
Create Date: 2022-11-29 16:00:43.701386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b1f11fe898'
down_revision = '62d6957e3cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('class_name', sa.String(length=64), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('permission_number', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requests_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_professor_id'), ['professor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requests_student_id'))
        batch_op.drop_index(batch_op.f('ix_requests_status'))
        batch_op.drop_index(batch_op.f('ix_requests_professor_id'))
        batch_op.drop_index(batch_op.f('ix_requests_owner'))
        batch_op.drop_index(batch_op.f('ix_requests_course_id'))
        batch_op.drop_index(batch_op.f('ix_requests_class_name'))

    op.drop_table('requests')
    # ### end Alembic commands ###
