"""empty message

Revision ID: 499e19a281e5
Revises: f6f196a6a908
Create Date: 2022-11-30 23:42:27.850146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499e19a281e5'
down_revision = 'f6f196a6a908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission_numbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_permission_numbers_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_numbers_course_id'))
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
