"""empty message

Revision ID: 8129902eb952
Revises: 499e19a281e5
Create Date: 2022-12-01 00:58:26.631612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8129902eb952'
down_revision = '499e19a281e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission_numbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_permission_numbers_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_numbers_request_id'))
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###
