"""empty message

<<<<<<<< HEAD:migrations/versions/d359948de76c_.py
Revision ID: d359948de76c
Revises: 
Create Date: 2022-12-06 13:20:14.769851
========
Revision ID: 98a80b3266d4
Revises: 
Create Date: 2022-11-30 02:02:25.488986
>>>>>>>> 38fb5b6cff63b25394307cef7db452a05077ece0:migrations/versions/98a80b3266d4_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/d359948de76c_.py
revision = 'd359948de76c'
========
revision = '98a80b3266d4'
>>>>>>>> 38fb5b6cff63b25394307cef7db452a05077ece0:migrations/versions/98a80b3266d4_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=20), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('college_course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_college_course_professor_id'), ['professor_id'], unique=False)

<<<<<<<< HEAD:migrations/versions/d359948de76c_.py
    op.create_table('permission_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_number', sa.Integer(), nullable=True),
    sa.Column('assigned', sa.Boolean(), nullable=True),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_numbers_assigned'), ['assigned'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_numbers_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_numbers_course_name'), ['course_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_numbers_permission_number'), ['permission_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_numbers_professor_id'), ['professor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_numbers_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_numbers_student_id'), ['student_id'], unique=False)

========
>>>>>>>> 38fb5b6cff63b25394307cef7db452a05077ece0:migrations/versions/98a80b3266d4_.py
    op.create_table('user',
    sa.Column('firstName', sa.String(length=64), nullable=True),
    sa.Column('lastName', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_professor', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('location', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_firstName'), ['firstName'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_lastName'), ['lastName'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('pn_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('class_name', sa.String(length=64), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('permission_number', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pn_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pn_requests_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pn_requests_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pn_requests_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_pn_requests_professor_id'), ['professor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pn_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pn_requests_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pn_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pn_requests_student_id'))
        batch_op.drop_index(batch_op.f('ix_pn_requests_status'))
        batch_op.drop_index(batch_op.f('ix_pn_requests_professor_id'))
        batch_op.drop_index(batch_op.f('ix_pn_requests_owner'))
        batch_op.drop_index(batch_op.f('ix_pn_requests_course_id'))
        batch_op.drop_index(batch_op.f('ix_pn_requests_class_name'))

    op.drop_table('pn_requests')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_lastName'))
        batch_op.drop_index(batch_op.f('ix_user_firstName'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
<<<<<<<< HEAD:migrations/versions/d359948de76c_.py
    with op.batch_alter_table('permission_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_numbers_student_id'))
        batch_op.drop_index(batch_op.f('ix_permission_numbers_request_id'))
        batch_op.drop_index(batch_op.f('ix_permission_numbers_professor_id'))
        batch_op.drop_index(batch_op.f('ix_permission_numbers_permission_number'))
        batch_op.drop_index(batch_op.f('ix_permission_numbers_course_name'))
        batch_op.drop_index(batch_op.f('ix_permission_numbers_course_id'))
        batch_op.drop_index(batch_op.f('ix_permission_numbers_assigned'))

    op.drop_table('permission_numbers')
========
>>>>>>>> 38fb5b6cff63b25394307cef7db452a05077ece0:migrations/versions/98a80b3266d4_.py
    with op.batch_alter_table('college_course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_college_course_professor_id'))

    op.drop_table('college_course')
    # ### end Alembic commands ###
